BaseURL: "http://blog.yhikishima.jp/"
LanguageCode: "en-us"
Title: "yhikishima's blog"

Params:
  Author: "yhikishima"
  Birth: "1985/12/12"
  DateForm: "2006/01/02"
  Job: "FrontEnd Enginner, Unity Enginner"
  GoogleAnalyticsUserID: "UA-68673100-1"
  GravatarHash: "/"
  Facebook: "yasuaki.hikishima"
  # Twitter: "Your ID."
  Github: "yhikishima"
  # Disqus: "Your Disqus."
  SyntaxHighlightTheme: "solarized_dark.min.css"
  ShowRelatedPost: True
  ShowTagCloud: True
  Description: "WEBのフロントエンド、ゲーム、漫画、小説、映画などを書いていきます。"
  Keywords: "WEB,FrontEnd,FrontEnginner,html,css,javascript,Unity,Game,Kindle,Manga,漫画,小説,映画"

Indexes:
  tag: "tags"
  group: "groups"

permalinks:
  post: /blog/:year/:month/:day/:title/

MetadataFormat: "yaml"

LastChange:
  Year: 2016
